[tools]
node = "latest"
opentofu = "latest"
terraform = "latest"
kubectl = "1.33.1"
go = "latest"
terraform-docs = "latest"
trivy = "latest"
cookiecutter = "latest"
pre-commit = "latest"
tflint = "latest"
pipx = "latest"
github-cli = "latest"
neovim = "latest"
tmux = "latest"
lazygit = "latest"
kubecolor = "latest"
krew = "latest"
k9s = "latest"
opencode = "latest"
helm = "latest"
oh-my-posh = "latest"
fzf = "latest"
azure-cli = "latest"
powershell = "latest"
zoxide = "latest"
cowsay = "latest"
arduino-cli = "latest"
kind = "latest"
argocd = "latest"
spacectl = "latest"
aws = { version = "latest", symlink_bins = "true" }
btop = "latest"
lazydocker = "latest"
tree-sitter = "latest"
