source ~/.exports
source ~/.aliases
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
#eval "$(oh-my-posh init zsh --config /home/josh/.config/oh-my-posh/tokyonight-night.omp.json)"
eval "$(oh-my-posh init zsh --config /home/josh/.config/oh-my-posh/catppuccin_custom.omp.json)"
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
